name: Send Slack Attendance Prompt

on:
  push:
  schedule:
    - cron: '30 2 * * 1-5'  # 8:00 AM IST, Monday to Friday
  workflow_dispatch:

jobs:
  send-prompt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run send_prompt.py
        run: python scripts/send_prompt.py
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_USER_IDS: ${{ secrets.SLACK_USER_IDS }}
